#!/bin/bash

# Catch exit signal (CTRL + C), to terminate the whole script.
trap "exit" INT

# Terminate script on error.
set -e

# Constant variable of the scripts' working directory to use for relative paths.
NETBIRD_HELPER_SCRIPT_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Import functions.
source "$NETBIRD_HELPER_SCRIPT_DIRECTORY/../functions/containers.sh"

# Constant variables for the checked-out service directories this helper
# reads from or writes into. NetBird has no reverse-proxy pull request of
# its own, unlike Traefik/Authelia: its dashboard/signal/relay/management
# use gRPC/HTTP2, and NetBird's own documented Traefik integration needs a
# dedicated TLS-passthrough proxy component this pinned upstream commit
# does not ship at all, retrofitting it would mean building new
# infrastructure upstream has not adopted, not layering on top of it. This
# stays a disclosed, deliberate exception to "front everything through
# Traefik", matching upstream's own admission that the login flow itself is
# only verified once deployed with a real domain.
NETBIRD_SERVICE_DIRECTORY="$CONTAINERS_DIRECTORY/networking/vpn/netbird"
AUTHELIA_SERVICE_DIRECTORY="$CONTAINERS_DIRECTORY/security/access/authelia"
AUTHELIA_OIDC_PROVIDER_TARGET="$AUTHELIA_SERVICE_DIRECTORY/configuration/oidc-provider.yml"
AUTHELIA_OIDC_SIGNING_KEY_FILE="$AUTHELIA_SERVICE_DIRECTORY/configuration/oidc-signing-key.pem"
POSTGRESQL_ENVIRONMENT_FILE="$CONTAINERS_DIRECTORY/databases/postgresql/.env"

# NetBird's dashboard/signal/relay/management all need to stay reachable
# from the public internet, unlike PostgreSQL/Redis, they are the VPN
# coordinator peers actually connect to. Preflight-check the fixed ports
# below (everything except coturn's UDP range, not practical to check
# individually and not fatal if one is briefly taken).
declare -A netbird_ports=(
    ["NETBIRD_DASHBOARD_HTTP_PORT"]="8080"
    ["NETBIRD_DASHBOARD_HTTPS_PORT"]="8443"
    ["NETBIRD_SIGNAL_PORT"]="10000"
    ["NETBIRD_RELAY_PORT"]="10001"
    ["NETBIRD_MANAGEMENT_PORT"]="10002"
)
for port_name in "${!netbird_ports[@]}"; do
    port="${netbird_ports[$port_name]}"
    if [ "$(is_port_available "$port")" == "false" ]; then
        log_error "Port $port ($port_name) is already in use."
        exit 1
    fi
done

postgresql_user=$(read_environment_value "$POSTGRESQL_ENVIRONMENT_FILE" "POSTGRESQL_USER")
postgresql_password=$(read_environment_value "$POSTGRESQL_ENVIRONMENT_FILE" "POSTGRESQL_PASSWORD")
postgresql_port=$(read_environment_value "$POSTGRESQL_ENVIRONMENT_FILE" "POSTGRESQL_PORT")

log_info "Ensuring the 'netbird' database exists..."
ensure_postgresql_database "netbird" "$postgresql_user"

domain=$(get_containers_domain)
netbird_domain="netbird.$domain"

# The OIDC client ID is not confidential (NetBird is registered as a public
# client, no client secret, see the comment on "authelia_oidc_client_id"
# below), but it must stay the same value on both sides, so it is persisted
# the same way a secret would be.
netbird_client_id=$(get_or_generate_shared_secret "CONTAINERS_NETBIRD_OIDC_CLIENT_ID" 16)

# Authelia's OpenID Connect provider needs its own signing key and HMAC
# secret. The key is a multi-line PEM, too large and unsafe for the
# single-line state file (see "get_or_generate_file_secret"), so it is
# persisted as its own file instead, generated once and reused, since
# regenerating it later would invalidate every previously issued token.
authelia_oidc_hmac_secret=$(get_or_generate_shared_secret "CONTAINERS_AUTHELIA_OIDC_HMAC_SECRET" 32)
authelia_oidc_private_key=$(get_or_generate_file_secret "$AUTHELIA_OIDC_SIGNING_KEY_FILE" "generate_rsa_private_key")

# NetBird's DataStoreEncryptionKey specifically documents "openssl rand
# -base64 32" in its own template, unlike every other generated secret in
# this repository, using the usual hexadecimal "generate_secret" here would
# not match that documented format.
source_state
if [ -n "$CONTAINERS_NETBIRD_DATASTORE_ENCRYPTION_KEY" ]; then
    netbird_datastore_encryption_key="$CONTAINERS_NETBIRD_DATASTORE_ENCRYPTION_KEY"
else
    netbird_datastore_encryption_key=$(openssl rand -base64 32)
    change_flag_value "CONTAINERS_NETBIRD_DATASTORE_ENCRYPTION_KEY" "$netbird_datastore_encryption_key"
fi

# Render Authelia's OIDC provider configuration, loaded as a second
# "--config" path by the Authelia override, on top of its own
# "configuration.yml", never merged into that tracked file directly. The
# key's PEM lines need more indentation than the "key: |" block scalar
# they sit under, matching YAML's own nesting rule.
indented_private_key=$(printf '%s\n' "$authelia_oidc_private_key" | sed 's/^/          /')
oidc_provider_temporary_file=$(mktemp)
cat >"$oidc_provider_temporary_file" <<EOF
---
# Generated by arch-tuner's netbird.sh helper, registering NetBird as a
# public OIDC client, so no third-party identity provider is needed. Never
# edited by hand, a rerun regenerates it from the same persisted secrets.
identity_providers:
  oidc:
    hmac_secret: '$authelia_oidc_hmac_secret'
    jwks:
      - key_id: 'netbird'
        algorithm: 'RS256'
        key: |
$indented_private_key
    clients:
      - client_id: '$netbird_client_id'
        client_name: 'NetBird'
        client_secret: ''
        public: true
        redirect_uris:
          - 'https://$netbird_domain:${netbird_ports[NETBIRD_DASHBOARD_HTTPS_PORT]}/peers'
          - 'https://$netbird_domain:${netbird_ports[NETBIRD_DASHBOARD_HTTPS_PORT]}/add-peers'
          - 'http://$netbird_domain:${netbird_ports[NETBIRD_DASHBOARD_HTTP_PORT]}/peers'
          - 'http://$netbird_domain:${netbird_ports[NETBIRD_DASHBOARD_HTTP_PORT]}/add-peers'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'offline_access'
        grant_types:
          - 'authorization_code'
          - 'refresh_token'
        response_types:
          - 'code'
        response_modes:
          - 'query'
        require_pkce: true
        pkce_challenge_method: 'S256'
        token_endpoint_auth_method: 'none'
        authorization_policy: 'one_factor'
...
EOF

log_info "Configuring Authelia's OIDC provider for NetBird..."
sudo mkdir -p "$(dirname "$AUTHELIA_OIDC_PROVIDER_TARGET")"
oidc_provider_changed="false"
if [ "$(compare_files "$AUTHELIA_OIDC_PROVIDER_TARGET" "$oidc_provider_temporary_file")" == "false" ]; then
    sudo cp "$oidc_provider_temporary_file" "$AUTHELIA_OIDC_PROVIDER_TARGET"
    sudo chmod 0600 "$AUTHELIA_OIDC_PROVIDER_TARGET"
    oidc_provider_changed="true"
fi
rm -f "$oidc_provider_temporary_file"

# Reapply Authelia, picking up its own override (the extra "--config" path
# and volume mount, unlikely to still be missing by now, but harmless to
# recheck). A no-op if that override did not change.
sh "$NETBIRD_HELPER_SCRIPT_DIRECTORY/authelia.sh"

# The OIDC provider file's content changing does not change Authelia's
# resolved Compose configuration (same mount path either way), so
# "authelia.sh"'s own "start_container_service" call above cannot detect
# it and never restarts the container on its own, force it here instead.
if [ "$oidc_provider_changed" == "true" ]; then
    log_info "Restarting Authelia to pick up the updated OIDC provider..."
    force_recreate_container_service "$AUTHELIA_SERVICE_DIRECTORY"
fi

# Known, non-secret values. "NETBIRD_AUTH_AUDIENCE" reuses the client ID,
# Authelia's default "aud" claim is the requesting client's ID. "api" is
# dropped from upstream's own template default scope list, it is an
# Auth0/Zitadel-specific scope Authelia does not define.
# shellcheck disable=SC2034 # Reason: nameref, read by render_environment_file by name, not read here.
declare -A netbird_known_values=(
    ["COMPOSE_PROJECT_NAME"]="netbird"
    ["POSTGRESQL_PORT"]="$postgresql_port"
    ["POSTGRESQL_USER"]="$postgresql_user"
    ["POSTGRESQL_PASSWORD"]="$postgresql_password"
    ["NETBIRD_DOMAIN"]="$netbird_domain"
    ["NETBIRD_DASHBOARD_HTTP_PORT"]="${netbird_ports[NETBIRD_DASHBOARD_HTTP_PORT]}"
    ["NETBIRD_DASHBOARD_HTTPS_PORT"]="${netbird_ports[NETBIRD_DASHBOARD_HTTPS_PORT]}"
    ["NETBIRD_SIGNAL_PORT"]="${netbird_ports[NETBIRD_SIGNAL_PORT]}"
    ["NETBIRD_RELAY_PORT"]="${netbird_ports[NETBIRD_RELAY_PORT]}"
    ["NETBIRD_MANAGEMENT_PORT"]="${netbird_ports[NETBIRD_MANAGEMENT_PORT]}"
    ["NETBIRD_AUTH_AUTHORITY"]="https://authelia.$domain"
    ["NETBIRD_AUTH_AUDIENCE"]="$netbird_client_id"
    ["NETBIRD_AUTH_CLIENT_ID"]="$netbird_client_id"
    ["NETBIRD_AUTH_SUPPORTED_SCOPES"]="openid profile email offline_access"
    ["NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT"]="https://authelia.$domain/.well-known/openid-configuration"
    ["NETBIRD_DATASTORE_ENCRYPTION_KEY"]="$netbird_datastore_encryption_key"
)
# shellcheck disable=SC2034 # Reason: nameref, read by render_environment_file by name, not read here.
declare -a netbird_secret_keys=("NETBIRD_RELAY_AUTH_SECRET" "NETBIRD_TURN_PASSWORD" "NETBIRD_TURN_TIME_BASED_SECRET")

log_info "Configuring NetBird..."
render_environment_file "$NETBIRD_SERVICE_DIRECTORY/template.env" "$NETBIRD_SERVICE_DIRECTORY/.env" netbird_known_values netbird_secret_keys

log_info "Starting NetBird..."
validate_container_service_configuration "$NETBIRD_SERVICE_DIRECTORY"
start_container_service "$NETBIRD_SERVICE_DIRECTORY"

log_success "NetBird is running!"
log_success "Dashboard: https://$netbird_domain:${netbird_ports[NETBIRD_DASHBOARD_HTTPS_PORT]} (log in with your admin credentials)"
log_success "coturn's UDP 3478 and 49152-65535 stay open, TURN relays cannot be reverse-proxied."
log_success "The login flow itself needs DNS for '$netbird_domain' pointed at this server to verify end to end."
