#!/bin/bash

# Flags to keep if the script ran up to a specific point or comppleted.
ESSENTIALS_COMPLETED=1
INTERFACE_COMPLETED=1
PRIVACY_COMPLETED=1
DEVELOPMENT_COMPLETED=1
DESKTOP_COMPLETED=1
COMPLETED_UP_TO_FIREWALL=1
SECURITY_COMPLETED=1
