#!/bin/bash

# Flags to mark the completion of each section.
INITIAL_SETUP=0
SYSTEM_RESET=1
ESSENTIALS_COMPLETED=1
INTERFACE_COMPLETED=1
PRIVACY_COMPLETED=1
DEVELOPMENT_COMPLETED=1
DESKTOP_COMPLETED=1
COMPLETED_UP_TO_FIREWALL=1
COMPLETED_UP_TO_MOUNT=1
SECURITY_COMPLETED=1
