# Custom abbreviations for terminal tools.
abbr cat "bat"
abbr ls "exa --long --all --icons --color=always --group-directories-first --git"
abbr cp "xcp"
abbr t "trash"
abbr tl "trash list"
abbr tea "trash empty --all"
abbr eva "calc"
abbr cd "z"
abbr cl "clear"
abbr find "fd"
abbr sed "sd"
abbr up "topgrade"
abbr mkdir "mkdir -p"
abbr jsn "jless"
abbr hlx "helix"
abbr h "history"
abbr ip "ip -br a | grep UP | awk '{print \"Interface: \" \$1 \"\nIPv4: \" \$3}'"
