# Custom aliases for terminal tools.
abbr cat "bat"
abbr ls "exa --long --all --icons --color=always --group-directories-first --git"
abbr cp "xcp"
abbr rm "trashy"
abbr rt "trashy list | fzf --multi | awk '{$1=$1;print}' | rev | cut -d ' ' -f1 | rev | xargs trashy restore --match=exact --force"
abbr et "trashy list | fzf --multi | awk '{$1=$1;print}' | rev | cut -d ' ' -f1 | rev | xargs trashy empty --match=exact --force"
abbr eva "calc"
abbr cd "z"
abbr find "fd"
abbr sed "sd"
abbr up "topgrade"
abbr mkdir "mkdir -p"
abbr jsn "jless"
abbr hlx "helix"
