# Custom aliases for terminal tools.
abbr cat "bat"
abbr ls "exa --long --all --icons --color=always --group-directories-first --git"
abbr cp "xcp"
abbr rm "rip"
abbr eva "calc"
abbr cd "z"
abbr find "fd"
abbr sed "sd"
abbr up "topgrade"
abbr mkdir "mkdir -p"
abbr jsn "jless"
abbr helix "hlx"
