# Custom aliases for terminal tools.
abbr cat "bat"
abbr ls "exa --git --icons --long --all --header --color=always --group-directories-first"
abbr cp "xcp"
abbr rm "rip"
abbr eva "calc"
abbr cd "z"
abbr find "fd"
abbr sed "sd"
abbr up "topgrade"
abbr mkdir "mkdir -p"
